name: Build Site
# run-name: ${{ github.actor }} is learning GitHub Actions
env:
  CI: false
on: 
    workflow_dispatch:
      inputs:
        reponame:
          description: 'Subroute of repo to build'
          required: false
          default: 'all'
          type: string
          


jobs:
  build-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
      - name: Install Fish
        run: |
          sudo apt-get update
          sudo apt-get install -y fish
      - name: Build Site
        run: |
          CI=false
          cd .github && ./build.fish ${{inputs.reponame}}
      - name: Push to github pages
        run: |
          git config --global user.name brohithkr
          git config --global user.email brohithkr@gmail.com
          cp -r .github/site/* .
          git status
          git add .
          git commit -m "site (automated)"
          git push          
